# Generated by Django 6.0.8 on 2026-08-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=80)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StreamState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False)),
                ('topic', models.CharField(blank=True, max_length=80)),
                ('rate', models.FloatField(default=1)),
                ('db_enabled', models.BooleanField(default=False)),
                ('config', models.JSONField(default=dict)),
                ('recent_msgs', models.JSONField(default=list)),
                ('msg_count', models.IntegerField(default=0)),
            ],
        ),
    ]
