# Generated by Django 6.0.8 on 2026-08-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_streamrow_streamstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(db_index=True, max_length=60)),
                ('maker', models.CharField(blank=True, max_length=200)),
                ('price', models.CharField(blank=True, max_length=60)),
                ('stock', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(db_index=True, max_length=40)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('date', models.CharField(blank=True, max_length=40)),
                ('views', models.IntegerField(default=0)),
                ('body', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, max_length=600)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
